<?php
/**
 * @file
 * Install, update, and uninstall functions for the MyModule module.
 */

/**
 * Upgrade from Drupal 7.
 */
function mymodule_update_1000() {
  // Convert D7 variables to config.
  $config = config('mymodule.settings');
  $config->set('opinion_of_backdrop', update_variable_get('mymodule_opinion_drupal', 'Awesome!'));
  $config->save();

  // Delete D7 variables.
  update_variable_del('mymodule_opinion_drupal');
}
